Customize upstream container image
Need to use the setup-docker-environment action to avoid:

```
Error: buildx failed with: ERROR: cache export feature is currently not
supported for docker driver. Please switch to a different driver (eg.
"docker buildx create --use")
```

Need to switch to refs/heads/main and login to github to avoid:

```
Fix Error: buildx failed with: ERROR: failed to solve: failed to fetch
anonymous token: unexpected status: 403 Forbidden
```